---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-admin-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-admin-user-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.admin: apiKey, login
  accounts.admin.enabled: "true"
