---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-homepage-user-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-homepage-user-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.hompage: apiKey, login
  accounts.hompage.enabled: "true"
