---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-cloudnativepg
  namespace: cnpg-cluster
type: Opaque
data:
  access_key: ZUlNTFpCUm0zWGxLeVRDZDVnNnoK
  access_secret_key: YVRjdW9aTmdJWGh0TVdGM0FVRUNKRzVqNmVROWkxdmZIMHNZN3l6awo=
