---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-cloudnativepg
  namespace: cnpg-cluster
type: Opaque
data:
  access_key: B1LmlhqtW6wyAneo923O
  access_secret_key: vgQ4mDnXyWAVG7ucFp5Mkeh6fIPL9J8raw3U0Kbi
