---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-cloudnativepg
  namespace: cnpg-cluster
type: Opaque
data:
  access_key: Sng0a0FXOEdWQ29LRDlpNXExM2M=
  access_secret_key: bWpuS2t4WHA0bEZRQ1pSaVRCYzE2MndFMFZxNXpPM1V1aEd0SDhZOQ==
