---
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-cloudnativepg
  namespace: cnpg-cluster
type: Opaque
stringData:
  access_key: JU1O0PBSY1KYQGCE6311
  access_secret_key: I715DzI0HnM9XJBxLqDRcM0s4+EvmC9y5evaN7G+
