---
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-cloudnativepg
  namespace: cnpg-cluster
type: Opaque
stringData:
  access_key: XSU6VOQUEPRJFJ3RIL6S
  access_secret_key: jLVB2+YAJ4MbZuy6meYn7q/QLPJKvzlWN6PC6Lf0
