---
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-cloudnativepg
  namespace: cnpg-cluster
type: Opaque
data:
  access_key: SlUxTzBQQlNZMUtZUUdDRTYzMTEK
  access_secret_key: STcxNUR6STBIbk05WEpCeExxRFJjTTBzNCtFdm1DOXk1ZXZhTjdHKwo=
