---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rustfs-secrets
  namespace: rustfs
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: rustfs/cloudnativepg-dev-backup
  refreshAfter: 60s
  destination:
    name: rustfs-cloudnativepg
    create: true
