# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: &app nessie
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: nessie
#     repoURL: https://charts.projectnessie.org
#     targetRevision: 0.105.7
#     helm:
#       valuesObject:
#         replicaCount: 1
#
#         log:
#           level: INFO
#           console:
#             enabled: true
#             threshold: ALL
#             json: false
#             format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n'
#           file:
#             enabled: false
#
#         versionStoreType: JDBC2
#         jdbc:
#           jdbcUrl: jdbc:postgresql://cnpg-cluster-rw.cnpg-cluster.svc.cluster.local:5432/nessie
#           secret:
#             name: nessie-db-credentials
#             username: username
#             password: password
#
#         # -- The Nessie catalog server configuration.
#         catalog:
#           # -- Whether to enable the REST catalog service.
#           enabled: true
#
#           iceberg:
#             defaultWarehouse: warehouse70ld
#             configDefaults: {}
#             configOverrides: {}
#
#             warehouses:
#               name: warehouse70ld
#               location: https://s3.garage.70ld.dev
#               configDefaults: {}
#               configOverrides: {}
#
#           storage:
#             s3:
#               defaultOptions:
#                 region: us-east-1
#                 endpoint: rustfs-svc.rustfs.svc.cluster.local:9000
#                 externalEndpoint: ~
#                 pathStyleAccess: ~
#                 accessPoint: ~
#                 allowCrossRegionAccessPoint: ~
#                 authType: STATIC
#                 requestSigningEnabled: true
#                 stsEndpoint: ~
#
#                 clientIam:
#                   enabled: false
#
#                 serverIam:
#                   enabled: false
#
#                 accessKeySecret:
#                   name: rustfs-nessie
#                   accessKeyId: accessKeyId
#                   secretAccessKey: secretAccessKey
#
#               buckets: []
#
#         metrics:
#           enabled: true
#           tags:
#             service: nessie
#
#         service:
#           type: LoadBalancer
#           ports:
#             - name: nessie-http
#               number: 19120
#           annotations: {}
#
#         resources:
#           limits:
#             cpu: 100m
#             memory: 128Mi
#           requests:
#             cpu: 100m
#             memory: 128Mi
#
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: *app
#
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
