---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-cloudnativepg
  namespace: cnpg-dev-cluster
type: Opaque
stringData:
  access_key: aC1EMt3TiJrF74cmk5A2
  access_secret_key: kzj4ZXuqoPCVQEpfR8TW3SA1iKw9yeF5xvUlcr6O
