---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-dev-cluster
  namespace: cnpg-dev-cluster
spec:
  description: '70LD CNPG Dev Cluster'
  instances: 1
  startDelay: 3600
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: '256MB'

  storage:
    storageClass: longhorn
    size: 8Gi

  bootstrap:
    initdb:
      database: dev
      owner: paul
      secret:
        name: cnpg-cluster-user

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-dev-rw-svc
              annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.7.81
            spec:
              type: LoadBalancer

  backup:
    retentionPolicy: "1d"

    barmanObjectStore:
      destinationPath: s3://cloudnativepg-dev-backup
      endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
      wal:
        compression: gzip
      s3Credentials:
        accessKeyId:
          name: rustfs-cloudnativepg
          key: access_key
        secretAccessKey:
          name: rustfs-cloudnativepg
          key: access_secret_key
