# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: rustfs-cloudnativepg
#   namespace: cnpg-dev-cluster
# type: Opaque
# stringData:
#   access_key: FwRzNQcSfdTtIyiHZEuG
#   access_secret_key: IMNb3eq2DCpUTZmj0xv4OX9LAcl5hnQE1g6kswYi
