---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.70ld.dev
  # --- API users ---
  accounts.admin: apiKey, login
  accounts.admin.enabled: "true"

  accounts.homepage: apiKey
  accounts.homepage.enabled: "true"

  # --- Keycloak SSO ---
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.70ld.dev/realms/master
    clientID: argocd
    enablePKCEAuthentication: true
    refreshTokenThreshold: 2m
    requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
