---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: 70LD Homelab
    theme: dark
    color: slate

    layout:
        Kubernetes:
            style: row
            columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Kubernetes:
        - AlertManager:
            icon: prometheus.png
            href: https://corfe-alertmanager.70ld.dev
            description: Alert Management

        - Docker Registry:
            icon: docker.svg
            href: https://corfe-registry.70ld.dev/v2/_catalog
            description: Container Registry

        - Grafana:
            icon: grafana.png
            href: https://corfe-grafana.70ld.dev/dashboards?starred
            description: Analytics & Monitoring

        - Longhorn:
            icon: longhorn.png
            href: https://corfe-longhorn.70ld.dev
            description: Distributed Block Storage

        - Prometheus:
            icon: prometheus.png
            href: http://corfe-prometheus.70ld.dev
            description: Analytics & Monitoring


  widgets.yaml: ""
  docker.yaml: ""
