---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    kubevirt.io/vm: &vm_name ubuntu-vm
  name: *vm_name
  namespace: kubevirt-vms
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: ubuntu-vm-rootdisk
      spec:
        source:
          registry:
            url: docker://quay.io/containerdisks/ubuntu:22.04
        storage:
          storageClassName: longhorn-kubevirt
          accessModes:
            - ReadWriteMany
          volumeMode: Block
          resources:
            requests:
              storage: 20Gi
  template:
    metadata:
      labels:
        kubevirt.io/vm: *vm_name
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
              bootOrder: 1
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-vm-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: sysadm
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  lock_passwd: false
              chpasswd:
                list: |
                  sysadm:ubuntu
                expire: false
              ssh_pwauth: true
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-vm-ssh
  namespace: kubevirt-vms
spec:
  type: LoadBalancer
  selector:
    vm.kubevirt.io/name: ubuntu-vm
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
