
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &app_name headlamp
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - app_name: *app_name
            project: default
            repo_url: https://github.com/mrpbennett/home-ops.git
            cluster: portland
            clusterURL: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{.app_name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{.project}}'
      source:
        chart: headlamp
        repoURL: https://kubernetes-sigs.github.io/headlamp/
        targetRevision: 0.45.0
        helm:
          valuesObject:
            replicaCount: 1
            config:
              inCluster: true
              inClusterContextName: "main"
              oidc:
                secret:
                  create: false
                externalSecret:
                  enabled: true
                  name: headlamp-oidc
                  hasScopes: true
                callbackURL: https://headlamp.70ld.dev/oidc-callback


            httpRoute:
              enabled: true
              parentRefs:
                - name: envoy-gateway-helm
                  namespace: envoy-gateway-system
                  sectionName: https
              hostnames:
                - headlamp.70ld.dev

      destination:
        server: '{{.clusterURL}}'
        namespace: '{{.app_name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 5m0s
            factor: 2
