---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &app_name tailscale
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - app_name: *app_name
            project: default
            repo_url: https://github.com/mrpbennett/home-ops.git
            cluster: portland
            clusterURL: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{.app_name}}-{{.cluster}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{.project}}'
      source:
        repoURL: '{{.repo_url}}'
        path: 'kubernetes/clusters/{{.cluster}}/apps/{{.app_name}}'
        targetRevision: HEAD
        directory:
          recurse: true
      destination:
        server: '{{.clusterURL}}'
        namespace: '{{.app_name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 5m0s
            factor: 2
