---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: rustfs
    repoURL: https://charts.rustfs.com
    targetRevision: 0.0.83
    helm:
      valuesObject:
        replicaCount: 1
        mode:
          standalone:
            enabled: true
            strategy:
              type: RollingUpdate
          distributed:
            enabled: false
        secret:
          rustfs:
            access_key: rustfsadmin
            secret_key: rustfsadmin
        config:
          rustfs:
            volumes: "/data/rustfs0"
            address: ":9000"
            console_enable: "true"
            console_address: ":9001"
            log_level: "info"
            region: "us-east-1"
            domains: "rustfs.70ld.dev"
            log_rotation:
              keep_files: 30
        service:
          type: LoadBalancer
        ingress:
          enabled: false
        storageclass:
          name: longhorn
          dataStorageSize: 10Gi
          logStorageSize: 512Mi

        extraManifests:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: rustfs-ingress
              namespace: rustfs
              annotations:
                nginx.ingress.kubernetes.io/rewrite-target: /
                nginx.ingress.kubernetes.io/affinity: cookie
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
                nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
                nginx.ingress.kubernetes.io/session-cookie-hash: sha1
                nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
                nginx.ingress.kubernetes.io/session-cookie-name: rustfs
                cert-manager.io/cluster-issuer: letsencrypt-cloudflare-dns-issuer
            spec:
              ingressClassName: nginx
              rules:
                - host: rustfs.70ld.dev
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: rustfs-svc
                            port:
                              number: 9001
              tls:
                - hosts:
                    - rustfs.70ld.dev
                  secretName: rustfs-ingress-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
