---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 11.3.2
    helm:
      valuesObject:
        namespace:
          labels:
            # Enforce Pod Security Standards with Namespace Labels
            # https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/enforce-version: latest
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/audit-version: latest
            pod-security.kubernetes.io/warn: privileged
            pod-security.kubernetes.io/warn-version: latest

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.13.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        extraObjects:
          - apiVersion: secrets.hashicorp.com/v1beta1
            kind: VaultConnection
            metadata:
              name: vault-connection
            spec:
              address: http://vault.vault.svc.cluster.local:8200

          - apiVersion: secrets.hashicorp.com/v1beta1
            kind: VaultAuth
            metadata:
              name: vault-auth
            spec:
              method: kubernetes
              mount: kubernetes
              kubernetes:
                role: vso-role
                serviceAccount: default
              vaultConnectionRef: vault-connection

          - apiVersion: secrets.hashicorp.com/v1beta1
            kind: VaultStaticSecret
            metadata:
              name: vault-seaweedfs-velero
            spec:
              vaultAuthRef: vault-auth
              mount: kv
              type: kv-v2
              path: seaweedfs/velero
              refreshAfter: 60s
              destination:
                name: seaweedfs-velero-secret
                create: true
                transformation:
                  template:
                    cloud: |
                      [default]
                      AWS_ACCESS_KEY_ID={{ .Secrets.AWS_ACCESS_KEY_ID }}
                      AWS_SECRET_ACCESS_KEY={{ .Secrets.AWS_SECRET_ACCESS_KEY }}

        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero
              default: true
              accessMode: ReadWrite
              credential:
                name: seaweedfs-velero-secret
                key: cloud
              config:
                region: 70ld-west-1
                s3ForcePathStyle: "true"
                s3Url: http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
                insecureSkipTLSVerify: "false"

          # Disable volume snapshots since only backing up Kubernetes resources
          volumeSnapshotLocation: []

        credentials:
          useSecret: true
          existingSecret: seaweedfs-velero-secret

        schedules:
          daily-backup:
            disabled: false
            schedule: '0 1 * * *'
            template:
              ttl: '72h0m0s'
              storageLocation: default
              includedNamespaces:
                - '*'
              excludedClusterScopedResources:
                - persistentVolumeClaims

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
