---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: metabase-svc
  namespace: metabase
spec:
  selector:
    app: metabase
  type: LoadBalancer
  ports:
    - name: metabase
      protocol: TCP
      port: 3000
      targetPort: 3000
