---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seaweedfs-loki
  namespace: logging
spec:
  vaultAuthRef: vault-secrets-operator/vault-auth
  mount: kv
  type: kv-v2
  path: seaweedfs/loki
  refreshAfter: 60s
  destination:
    name: seaweedfs-loki
    create: true
