# ---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultStaticSecret
# metadata:
#   name: myapp-secrets
#   namespace: default
# spec:
#   vaultAuthRef: vault-auth
#   mount: secret
#   type: kv-v2
#   path: myapp/config
#   refreshAfter: 60s
#   destination:
#     name: myapp-k8s-secret # The K8s Secret that gets created
#     create: true
#   rolloutRestartTargets: # THIS is the nice VSO feature
#     - kind: Deployment
#       name: myapp
