---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: vault-secrets-operator
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault-secrets-operator
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: vault-connection
  allowedNamespaces:
    - "*"
  kubernetes:
    role: vso-role
    serviceAccount: default
