---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-dev-daily-backup
spec:
  # daily @ midnight
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-dev-cluster
