---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: corfe-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/mrpbennett/home-ops.git
        revision: HEAD
        directories:
          - path: kubernetes/clusters/corfe/apps/*
  template:
    metadata:
      name: 'corfe-{{.path.basename}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/mrpbennett/home-ops.git
        path: '{{.path.path}}'
        targetRevision: HEAD
        directory:
          recurse: true
      destination:
        name: corfe
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 5m0s
            factor: 2
