# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-cluster-user
  namespace: cnpg-prod-cluster
type: Opaque
stringData:
  username: paul
  password: password
