---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-oidc-cm
  namespace: argocd
data:
  url: https://argocd.70ld.dev
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.70ld.dev/realms/master
    clientID: argocd
    enablePKCEAuthentication: true
    refreshTokenThreshold: 2m
    requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
