---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    gateway: true
  settings.yaml: |
    title: 70LD Homelab
    theme: dark
    color: slate
    useEqualHeights: true

    layout:
      Infra:
        style: row
        columns: 2

      Observability:
        icon: mdi-chart-line
        style: row
        columns: 4

      Storage:
        icon: mdi-harddisk
        style: row
        columns: 4

      Data:
        icon: mdi-database
        style: row
        columns: 3

      Platform:
        icon: mdi-kubernetes
        style: row
        columns: 2

      Security:
        icon: mdi-shield-lock
        style: row
        columns: 2

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Infra:
      - Promxox:
          icon: proxmox.png
          href: http://192.168.7.5:8006
          description: Hypervisor
          widget:
            type: proxmox
            url: http://192.168.7.5:8006
            username: api@pam!homepage
            password: b09ab10a-8725-4f28-9fad-9d116790b82f
            fields: ["vms", "lxc", "resources.cpu", "resources.mem"]

      - AdGuard Home:
            icon: adguard-home.png
            href: http://dns.70ld.local
            description: Primary DNS
            widget:
                type: adguard
                url: http://192.168.4.2
                username: admin
                password: 123qwe!!
                fields: ["queries", "blocked", "filtered", "latency"]

    - Observability:
      - AlertManager:
          icon: prometheus.png
          href: https://alertmanager.70ld.dev
          description: Alert Management

      - Headlamp:
          icon: headlamp.png
          href: https://headlamp.70ld.dev
          description: Cluster Monitoring

      - Grafana:
          icon: grafana.png
          href: https://grafana.70ld.dev/dashboards?starred
          description: Analytics & Monitoring

      - Prometheus:
          icon: prometheus.png
          href: http://prometheus.70ld.dev
          description: Analytics & Monitoring

    - Storage:
      - Longhorn:
          icon: longhorn.png
          href: https://longhorn.70ld.dev
          description: Persistent Block Storage

      - SeaweedFS:
          icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/seaweedfs.svg
          href: http://192.168.6.2:23646/admin
          description: Object Storage

      - TrueNAS Scale:
          icon: truenas-scale.svg
          href: http://192.168.4.50
          description: Actually WD Cloud

      - WDCloud:
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/western-digital.svg
          href: http://192.168.4.110
          description: WD Cloud

    - Data:
      - ChartDB:
          icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/chartdb.png
          href: https://chartdb.70ld.dev
          description: Self hosted ERD

      - PGAdmin:
          icon: postgres.png
          href: https://pgadmin.70ld.dev
          description: Postgres Management

      - Trino:
          icon: https://cdn.simpleicons.org/trino/FFFFFF
          href: http://trino.70ld.dev
          description: SQL Query Engine

    - Platform:

      - Airflow:
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/apache-airflow.svg
          href: https://192.168.7.69
          description: Workflow Management Platform

      - ArgoCD:
          icon: argo-cd.png
          href: https://argocd.70ld.dev
          description: Continuous Delivery
          widget:
            type: argocd
            url: https://argocd.70ld.dev
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJob21lcGFnZTphcGlLZXkiLCJuYmYiOjE3OTEyODUzMjEsImlhdCI6MTc5MTI4NTMyMSwianRpIjoiYWEwYzE0YjctMmQwMy00ZTg4LWI5ZTctN2EyZGVjOWNkZTJiIn0.O8O5e7IDTUtT2IRefh3bn1Hym9DqlyMBwhY2nPQ7n5A

    - Security:

      - Keycloak:
          icon: keycloak.png
          href: https://keycloak.70ld.dev
          description: Auth & OIDC

      - Vault:
          icon: vault-light.png
          href: http://vault.70ld.dev
          description: Secret Management

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "portland"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  docker.yaml: ""
