---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: 70LD Homelab
    theme: dark
    color: slate

    layout:
        Network:
            style: row
            columns: 1

        Kubernetes:
            style: row
            columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Network:
      - AdGuard Home:
            icon: adguard-home.png
            href: http://dns.70ld.local
            description: Primary DNS
            widget:
                type: adguard
                url: http://192.168.4.2
                username: admin
                password: 123qwe!!
                fields: ["queries", "blocked", "filtered", "latency"]

    - Kubernetes:
        - AlertManager:
            icon: prometheus.png
            href: https://alertmanager.70ld.dev
            description: Alert Management

        - ArgoCD:
            icon: argo-cd.png
            href: https://argocd.70ld.dev
            description: Continuous Delivery

        - ChartDB:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/chartdb.png
            href: https://chartdb.70ld.dev
            description: Self hosted ERD

        - Grafana:
            icon: grafana.png
            href: https://grafana.70ld.dev/dashboards?starred
            description: Analytics & Monitoring

        - Headlamp:
            icon: headlamp.png
            href: https://headlamp.70ld.dev
            description: Cluster Monitoring

        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.70ld.dev
            description: Persistent Block Storage

        - PGAdmin:
            icon: postgres.png
            href: https://pgadmin.70ld.dev
            description: Postgres Management

        - Prometheus:
            icon: prometheus.png
            href: http://prometheus.70ld.dev
            description: Analytics & Monitoring

        - Trino:
            icon: https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg
            href: http://192.168.7.81
            description: SQL Query Engine

        - TrueNAS Scale:
            icon: truenas-scale.svg
            href: http://192.168.4.110
            description: Actually WD Cloud

        - Vault:
            icon: vault-light.png
            href: http://vault.70ld.dev
            description: Secret Management

  widgets.yaml: ""
  docker.yaml: ""
