---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: monitoring
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-role
    serviceAccount: default
  vaultConnectionRef: vault-connection
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: alertmanager/discord
  refreshAfter: 60s
  destination:
    name: alertmanager-discord
    create: true
