---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: trino
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: trino
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: vault-connection
  kubernetes:
    role: vso-role
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trino-secrets
  namespace: trino
spec:
  type: kv-v2
  mount: kv
  path: trino
  refreshAfter: 60s
  vaultAuthRef: vault-auth
  destination:
    create: true
    name: trino-secrets
  rolloutRestartTargets:
    - kind: Deployment
      name: trino-coordinator
    - kind: Deployment
      name: trino-worker
