---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trino-secrets
  namespace: trino
spec:
  type: kv-v2
  mount: kv
  path: trino
  refreshAfter: 60s
  vaultAuthRef: vault-secrets-operator/vault-auth
  destination:
    create: true
    name: trino-secrets
  rolloutRestartTargets:
    - kind: Deployment
      name: trino-coordinator
    - kind: Deployment
      name: trino-worker
