---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-adguard
  namespace: external-dns
type: Opaque
stringData:
  ADGUARD_URL: http://192.168.4.2
  ADGUARD_USER: admin
  ADGUARD_PASSWORD: 123qwe!!

