---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudnativepg-prod-superuser
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: cloudnativepg/prod/superuser
  refreshAfter: 60s
  destination:
    name: cnpg-cluster-superuser
    create: true

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudnativepg-prod-main-user
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: cloudnativepg/prod/main-user
  refreshAfter: 60s
  destination:
    name: cnpg-cluster-user
    create: true

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudnativepg-prod-authentik
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: cloudnativepg/prod/authentik
  refreshAfter: 60s
  destination:
    name: cnpg-authentik-user
    create: true

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seaweedfs-cloudnativepg-prod-backup
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: seaweedfs/cloudnativepg-prod-backup
  refreshAfter: 60s
  destination:
    name: seaweedfs-cloudnativepg
    create: true
